### PR TITLE
Typography,lists

### PR DESCRIPTION
**Pull request by NeerajVodala**
## Added Components:
- Typography
    - Heading
    - Text weight
    - Text alignment
- List
    - Inline List
    - Stacked List 

Deploy preview-1:  https://deploy-preview-6--cluach.netlify.app/docs/typography.html
Deploy preview-2:  https://deploy-preview-6--cluach.netlify.app/docs/components/list.html

Images for reference:
list-inline
list-stacked
headings
text-weight
text-alignment

### CODE REVIEW

**Review by rishmi5h — COMMENTED** [review]
looks good,
I guess in typography you can add gray text and small text as mentioned in the LMS.
rest all looks good.

**Comment by LordUttam** [comment]
Looks really good but add the gray text. It's a requirement mentioned in LMS.

**Comment by NeerajVodala** [comment]
> looks good, I guess in typography you can add gray text and small text as mentioned in the LMS. rest all looks good.

Thanks for the review, added colored text.

**Comment by NeerajVodala** [comment]
> Looks really good but add the gray text. It's a requirement mentioned in LMS.

Thanks for the review, added colored text.

**Review by rishmi5h — APPROVED** [review]

**Pull request merged**
